Name: WinSrumApplicationResourceUsage
Desc: Windows SRUM Application Resource Usage
Table:
  - TableName: lv1_os_win_srum_application_resource_usage
    Columns:
      - par_id
      - case_id
      - evd_id
      - srum_id_number
      - srum_entry_creation
      - application
      - facetime
      - cpu_time_in_forground

    Types:
      - [VARCHAR(255), NOT NULL]
      - [VARCHAR(255), NOT NULL]
      - [VARCHAR(255), NOT NULL]
      - [TEXT]
      - [TEXT]
      - [TEXT]
      - [TEXT]
      - [TEXT]